# This is a basic workflow to help you get started with Actions

name: Push nuget

# Controls when the action will run. 
on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ main ]
    paths: 
      - 'release.history'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: restore tools
        run: dotnet tool restore
      - name: run push-package
        shell: pwsh
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        run: push-package.ps1
